### ISSUE TITLE
Wrap additional functions in `scico.scipy.special`

### ISSUE THREAD

**Issue by Michael-T-McCann** [lanl/scico#166]
(Adapted from a TODO left in the code.) We currently do not wrap `lpmn` or `lpmn_values` because they take integers as their first argument and ndarray as their last argument, and this does not work with the current `_block_array_ufunc_wrapper`.

**Comment by bwohlberg** [comment]
@Michael-T-McCann: Was this perhaps resolved in #259?

**Comment by Michael-T-McCann** [comment]
> @Michael-T-McCann: Was this perhaps resolved in #259?

This is not resolved; these still aren't wrapped. However, I vote to close on the basis that I don't think the goal here should be to wrap every conceivable function, but rather to wrap the functions that somebody wants to use with block arrays.

**Comment by bwohlberg** [comment]
Fair enough. Closing for now.
